# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Test/final_project/final_project.cache/wt [current_project]
set_property parent.project_path D:/Test/final_project/final_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.4 [current_project]
set_property ip_output_repo d:/Test/final_project/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Test/final_project/final_project.srcs/sources_1/imports/hdl_generated/bitwidths.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/cnn_types.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/convElement.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/firstLayer.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/neighExtractor.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/sumElement.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/taps.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/new/multi_conv_comb.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/convLayer.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/inter_layer_union.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/maxPool.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/poolH.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/poolLayer.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/multi_conv_comb/multi_conv_comb.srcs/sources_1/imports/MasterThesis/Components/poolV.vhd
  D:/Test/final_project/final_project.srcs/sources_1/imports/Test/dsp_layer/dsp_layer.srcs/sources_1/new/dsp_layer.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top multi_conv_comb -part xc7z045ffg900-2


write_checkpoint -force -noxdef multi_conv_comb.dcp

catch { report_utilization -file multi_conv_comb_utilization_synth.rpt -pb multi_conv_comb_utilization_synth.pb }
